Nordix/Meridio

cmd/frontend/main.go
cmd/frontend/service.go
cmd/proxy/main.go
pkg/client/client.go
pkg/kernel/route.go
pkg/nsm/interfacemonitor/common.go
pkg/nsm/interfacename/client.go
pkg/nsm/interfacename/client_test.go
pkg/nsm/interfacename/common.go
pkg/nsm/interfacename/server_test.go
pkg/proxy/proxy.go

Scaling in an LB works now. (Then scaling out LBs again also seems to work.) 
note: requires vpp-forwarder that's based on v1.0.0, so pull updated image registry.nordix.org/cloud-native/nsm/cmd-forwarder-vpp:fwsel0
Closes #29

proxy; fix LB scale-in

---

build/load-balancer/Dockerfile
cmd/target/main.go
docs/demo/readme.md
docs/demo/scripts/kind/external-host.sh
docs/demo/xcluster.md
examples/target/helm/templates/target.yaml
examples/target/helm/values.yaml
pkg/configuration/watcher.go
pkg/loadbalancer/loadbalancer.go

- Fix target scale-in 
- NFQLB updated to 0.1.1
- Ambassador demo instructions (connect/disconnect a trench, request/close a stream)

Target scale-in, NFQLB, Ambassador instructions 

---

cmd/load-balancer/main.go
docs/demo/deployments/xcluster/ovl/meridio/README.md
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/11hosts.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/11xnet.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/20bridge.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/30kube-prep.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/32cri-plugin.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/32kube-node.rc
docs/demo/deployments/xcluster/ovl/meridio/default/etc/init.d/91multus.rc
docs/demo/deployments/xcluster/ovl/meridio/default/tmp/init.d/31kube-master.rc
docs/demo/deployments/xcluster/ovl/meridio/default/tmp/init.d/92vlan-nad.rc
docs/demo/deployments/xcluster/ovl/meridio/default/tmp/kubernetes/gw.yaml
docs/demo/deployments/xcluster/ovl/meridio/default/tmp/kubernetes/gw_dummy.yaml
docs/demo/deployments/xcluster/ovl/meridio/default/tmp/kubernetes/schedulerpolicy
docs/demo/deployments/xcluster/ovl/meridio/gateway/Dockerfile
docs/demo/deployments/xcluster/ovl/meridio/gateway/README
docs/demo/deployments/xcluster/ovl/meridio/gateway/bird-common.conf
docs/demo/deployments/xcluster/ovl/meridio/gateway/bird-gw.conf
docs/demo/deployments/xcluster/ovl/meridio/gateway/bird-tg.conf
docs/demo/deployments/xcluster/ovl/meridio/gateway/gw-tg.sh
docs/demo/deployments/xcluster/ovl/meridio/gateway/gw.sh
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/.helmignore
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/Chart.yaml
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/templates/_helpers.tpl
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/templates/gateway.yaml
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/templates/tg.yaml
docs/demo/deployments/xcluster/ovl/meridio/helm/gateway/values.yaml
docs/demo/deployments/xcluster/ovl/meridio/tar
docs/demo/xcluster.md

The OVL at subject can be used to test Meridio
on xcluster.

demo; move xcluster ovl to meridio repo

---

docs/demo/scripts/spire-config.sh
docs/demo/scripts/spire.sh
pkg/target/conduit/conduit.go

Added refresh NetworkServiceClient chain element to target
NSC, thus the connection gets automatically renewed.
Closes: #71

target; NSC connection to proxy is renewed

---

pkg/configuration/reader/model.go

They will shown to be 0 when undefined, which is confusing

cm reader: omitempty for BFD/BGP specific params when undefined

---

pkg/configuration/reader/reader.go
pkg/configuration/reader/reader_test.go
pkg/configuration/watcher.go

change unmarshal to unmarshalStrict to restrict unknown fields

watcher: fix event handler in unmarshal vip

---

docs/demo/deployments/xcluster/ovl/meridio/README.md
docs/demo/deployments/xcluster/ovl/meridio/tar
docs/demo/xcluster.md

Verified with Operator version: f4080dcc20e6a1ddb71426d6f35657f1b061e892

docs; xcluster user guide update

---

docs/readme.md
test/e2e/e2e.md
test/e2e/e2e_suite_test.go
test/e2e/ingress_traffic_test.go
test/e2e/manifest/meridio-trench-b.yaml
test/e2e/multi_trenches_test.go
test/e2e/operator/operator.go
test/e2e/scaling_test.go
test/e2e/target_test.go

- update submodule with new attractor format
- adding back multi-trench test
- add manifests for deploying meridio from operator

Adapt e2e test to test with operator

---

pkg/target/conduit/conduit.go

Fixed: return nil -> return err

---

cmd/load-balancer/main.go
pkg/kernel/interface.go
pkg/kernel/monitor.go
pkg/kernel/utils.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/networking/ifaces.go

lb; process pending Targets when new NSM interface appears

---

Makefile
build/frontend/Dockerfile
build/ipam/Dockerfile
build/load-balancer/Dockerfile
build/nsp/Dockerfile
build/proxy/Dockerfile
build/tapa/Dockerfile
cmd/frontend/main.go
cmd/ipam/main.go
cmd/load-balancer/main.go
cmd/nsp/main.go
cmd/proxy/main.go
cmd/tapa/main.go
docs/demo/deployments/xcluster/ovl/forwarder-test/forwarder-test.sh
docs/demo/deployments/xcluster/ovl/forwarder-test/images/ipam/tar
docs/demo/deployments/xcluster/ovl/forwarder-test/images/load-balancer/tar
docs/demo/deployments/xcluster/ovl/forwarder-test/images/meridio-app/tar
docs/demo/deployments/xcluster/ovl/forwarder-test/images/nsp/tar
docs/demo/deployments/xcluster/ovl/forwarder-test/images/proxy/tar
docs/demo/deployments/xcluster/ovl/forwarder-test/images/tapa/tar

Fixes https://github.com/Nordix/Meridio/issues/183
If you have opinions on the help text, please write _exactly_ what you think it should be an I will replace it. I don't really care myself and will not indulge in any debate.

Add --version and --help to binaries

---

docs/demo/deployments/xcluster/ovl/forwarder-test/default/etc/kubernetes/forwarder-test-local/load-balancer-template.yaml
docs/demo/deployments/xcluster/ovl/forwarder-test/default/etc/kubernetes/forwarder-test/load-balancer-template.yaml
docs/demo/deployments/xcluster/ovl/forwarder-test/default/etc/kubernetes/forwarder-test/nsc-template.yaml
docs/demo/deployments/xcluster/ovl/forwarder-test/default/etc/kubernetes/forwarder-test/nse-template.yaml

ovl/forwarder-test; remove refs to nsm v1.3.0-rc.1

---

cmd/load-balancer/egress.go

Due to the new keepalive mechanism, the FE was refreshing its entry in the NSP service every x (30) seconds, the NSP was receiving the changes and was forwarding it to every component which uses the watch functions. The LB were then receiving the changes about the FE every 30 seconds and were doing some unecessary actions.
The ideal solution would be to have cache in the NSP, this will be implemented in the future.
Related issue: https://github.com/Nordix/Meridio/issues/216

Fix egress traffic failover issue due to keepalive

---

pkg/proxy/vip.go

Fix ERRO printouts in the proxy logs

---

docs/demo/deployments/xcluster/ovl/forwarder-test/default/etc/kubernetes/forwarder-test/load-balancer-template.yaml
docs/trouble-shooting/README.md
docs/trouble-shooting/traffic-path.svg

Add a Meridio Troubleshooting Guide.

Trouble shooting guide

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

Issue/PR template and Code of conduct

---

pkg/ipam/storage/sqlite/sqlite.go

* Add check if prefix in nil in IPAM SQLite storage
/
- Purpose
- Test

Fix nil pointer issue in IPAM on release

---

docs/trouble-shooting/README.md

Describe `nfqlb` flow-trace in the troubleshooting guide.
- Purpose
- Test

Flow trace doc

---

build/load-balancer/Dockerfile

Update to NFQLB 1.1.0
https://github.com/Nordix/nfqueue-loadbalancer/releases/tag/1.1.0
- Purpose
- Test

Update to NFQLB 1.1.0

---

pkg/ambassador/tap/conduit/configuration.go

* If a Close is called, and the TAPA has to disconnect the conduit while the VIP addresses are updated at the same time, then the TAPA was blocked due to the wait the Stop function of the conduit configuration handler. The SetVIP was waiting for the mutex to be unlocked while the Disconnect was waiting for the Configuration Handler to be finished (which was stucked due to the SetVIP).
* Refactoring on the way the VIP and streams are handled. If the process takes too much time, the intermediate values are ignored (the values received between the very last reception and the one currently in process).
/
- Purpose
- Test

Fix TAPA blocked Close if VIPs are updated at the same time

---

pkg/security/credentials/credentials.go

The `source` variable can contain nil but was used anyway.
And structured logs added.
- Purpose
- Test

Fix potential crash while getting TLS credentials

---

cmd/frontend/internal/frontend/service.go
cmd/load-balancer/egress.go
cmd/load-balancer/main.go
pkg/endpoint/endpoint.go
pkg/health/checker.go
pkg/health/connection/connection.go
pkg/health/probe/probe.go
pkg/health/wrapper.go
pkg/kernel/nftset.go
pkg/loadbalancer/flow/flow.go
pkg/loadbalancer/nfqlb/netfilter.go
pkg/loadbalancer/nfqlb/nfqlb.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/nat/handler.go
pkg/nsm/client.go
pkg/nsm/interfacemonitor/common.go

Use structured logging in load-balancer
#253
- Purpose
- Test

Use structured logging in load-balancer

---

cmd/nsp/main.go
pkg/nsp/registry/keepalive/keepalive.go
pkg/nsp/registry/keepalive/keepalive_test.go
pkg/nsp/server.go

Use structured logging in nsp
#253
- Purpose
- Test

Use structured logging in nsp

---

cmd/ipam/main.go
pkg/ipam/server.go
pkg/ipam/trench/watcher.go

Use structured logging in ipam
#253 
- Purpose
- Test

Use structured logging in ipam

---

cmd/tapa/main.go
pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go
pkg/ambassador/tap/conduit/configuration.go
pkg/ambassador/tap/conduit/manager.go
pkg/ambassador/tap/conduit/manager_test.go
pkg/ambassador/tap/stream/factory_test.go
pkg/ambassador/tap/stream/stream.go
pkg/ambassador/tap/stream/stream_test.go
pkg/ambassador/tap/tap.go
pkg/ambassador/tap/trench/conduit.go
pkg/ambassador/tap/trench/trench.go
pkg/ambassador/tap/trench/trench_test.go
pkg/ambassador/tap/utils.go

Use structured logging in tapa
#253
- Purpose
- Test

Use structured logging in tapa

---

cmd/proxy/internal/client/client.go
cmd/proxy/internal/client/fullmesh.go
cmd/proxy/internal/service/client.go
cmd/proxy/internal/service/server.go
cmd/proxy/main.go
pkg/proxy/health/client.go
pkg/proxy/proxy.go
pkg/proxy/vip.go

Add structured logging in proxy
#253 
- Purpose
- Test

Add structured logging in proxy

---

cmd/nsp/main.go
pkg/nsm/interfacemonitor/common.go

Re-add an accidentally removed line
Re-enable TRACE in cmd/nsp
- Purpose
- Test

Correct structured logging

---

pkg/configuration/manager/server.go
pkg/configuration/monitor/monitor.go
pkg/kernel/fwmark.go
pkg/nat/nat.go
pkg/nsm/endpoint/endpoint.go
pkg/nsm/endpoint/server.go

Made `grep -Fr 'logrus"' pkg` and replaces all logrus calls with Meridio log.
#253
- Purpose
- Test

Structure Logging; mop-up

---

docs/trouble-shooting/README.md

For structured logging
- Purpose
- Test

Update logging in the trouble-shooting guide

---

Makefile
docs/security-scan.md
hack/parse_security_scan.sh

- Json output for security scanner
- Json parser for trivy, grype and nancy
- Documentation
/
- Purpose
- Test

Security scan output to json and documentation

---

build/load-balancer/Dockerfile

Fix traffic outage on flow update + stream redeployment
https://github.com/Nordix/Meridio/issues/302
- Purpose
- Test

Uplift to NFQLB 1.1.2

---

.gitignore
docs/demo/scripts/kind/Dockerfile
docs/demo/scripts/kind/Makefile
docs/demo/scripts/kind/readme.md
test/e2e/environment/kind-helm/test-scope.yaml

Environment makefile allows users to install Kind, deploy a Kind Cluster with the gateways, Install and NSM. Version of Kubernetes, IP Family and Kubernetes version are parameters.
Test-scope.yaml provides allowed versions and IP-Family to be run in the CI.
- Purpose
- Test

Environment makefile and test-scope.yaml

---

test/integration/attractor_test.go
test/integration/conduit_test.go
test/integration/e2e_suite_test.go
test/integration/flow_test.go
test/integration/gateway_test.go
test/integration/stream_test.go
test/integration/trench_test.go
test/integration/vip_test.go

Fix integration tests blocking the CI

---

pkg/ambassador/tap/conduit/configuration.go

Max-Target must be set to 100 as default value if the NSP does not send any value. This happens if Meridio <= v0.8.0 is used with TAPA >= v0.9.0
1. What would be the way to solve this issue? 
- Solving the current way?
- Creating a new NSP API Version?
https://github.com/Nordix/Meridio/issues/323
- Purpose
- Test

Fix max-target in TAPA if no value sent by NSP

---

website/docusaurus.config.js

This is used for analytics and website SEO.
/
- Purpose
- Test

Add gtag ID on website

---

pkg/loadbalancer/stream/target.go

The internal structure was exposed and GetIdentifier() repeated the extract on every call. This PR simplifies the code and extract the identifier once.
The update is backward compatible, but the `NewTarget()` function should really be `newTarget()` to reflect that the target is not used outside the `stream` package.
N/A
- Purpose
- Test

Simplify target and make the internal struct private

---

Makefile

Fix Linter for golang 1.20
/
- Purpose
- Test

Fix Linter for golang 1.20

---

build/base-image/Dockerfile
build/operator/Dockerfile
config/operator/operator.yaml

* Update to alpine 3.17.2
* Update base-image of operator to common base-image
- Purpose
- Test

Update base-image version and operator base-image

---

Makefile
build/frontend/Dockerfile
build/ipam/Dockerfile
build/nsp/Dockerfile
build/operator/Dockerfile
build/proxy/Dockerfile
build/stateless-lb/Dockerfile
build/tapa/Dockerfile
examples/target/build/example-target/Dockerfile
examples/target/go.mod
go.mod
pkg/ambassador/tap/stream/stream.go
pkg/nsm/interfacename/generator.go

- go.mod to 1.20
- Dockerfile updated
- Replace deprecated rand.Seed function
- Update golangci-lint version
/
- Purpose
- Test

Update to Go 1.20

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Versions documentation and test-scope

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release to v1.0.6 (documentation)

---

pkg/ambassador/tap/stream/stream.go
pkg/ambassador/tap/stream/stream_test.go

Improvement for the refresh mechanism in the TAPA when the target in the NSP is in disabled state or no longer existing. The TAPA is now ignoring itself from the list of identifier in use, so it can now refresh its registration if it became disable in the NSP.
/
- Purpose
- Test

TAPA refresh with disabled target

---

cmd/stateless-lb/egress.go
cmd/stateless-lb/main.go
pkg/endpoint/endpoint.go

Do not allow NSE unregister() to block indefinitely.
In stateless-lb unregistering the LB endpoint (NSE) can get stuck, thus blocking the goroutine in processing new FE related events.
https://github.com/Nordix/Meridio/issues/355
- Purpose
- Test

LB; nsm endpoint unregister with timeout

---

cmd/proxy/internal/client/utils.go
cmd/tapa/main.go

OPA features are not used in Meridio
- Purpose
- Test

Remove NSM authorize chain element

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.0.8 (Documentation)

---

pkg/controllers/attractor/nse-vlan.go
pkg/controllers/attractor/stateless-lb-frontend.go
pkg/controllers/common/models.go
pkg/controllers/common/models_test.go
pkg/controllers/conduit/proxy.go
pkg/controllers/trench/ipam.go
pkg/controllers/trench/nsp.go

If the order of the environment variable is not consistent, then the resources could be reconciled forever.
- Purpose
- Test

Fix env variable reconciler

---

pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/trench/configuration.go

TAPA was getting stuck without the possibility to close streams if a conduit gets stuck on the SetVIPs phase (NSM returning an error). The Disconnect would wait for the SetVIPs function to be finished.
- Purpose
- Test

Fix TAPA stuck on SetVIPs

---

go.mod
go.sum

Requires an update of https://github.com/grpc-ecosystem/grpc-health-probe
https://github.com/advisories/GHSA-2c7c-3mj9-8fqh
- Purpose
- Test

Fix GHSA-2c7c-3mj9-8fqh

---

build/base-image/Dockerfile

Update /grpc-health-probe to v0.4.23
https://github.com/Nordix/Meridio/pull/482
https://github.com/advisories/GHSA-2c7c-3mj9-8fqh
- Purpose
- Test

Fix GHSA-2c7c-3mj9-8fqh (grpc-health-probe)

---

readme.md

Update events in readme

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.0.15 (Documentation)

---

pkg/nsm/interfacename/cache.go
pkg/nsm/interfacename/cache_test.go

Stop releaseTrigger() invoked goroutine(s) right away when Release() is cancelled in InterfaceNameChache.
Thus, avoid accumulation of such goroutines (leading to increased memory footprint) for example when TAPA must keep trying to establish connection with the local Proxy for longer time.
#500 
- Purpose
- Test

TAPA; fix goroutine cleanup in intefacename cache

---

docs/components/frontend.md
docs/components/stateless-lb.md

Update component description of stateless-lb and frontend.
https://github.com/Nordix/Meridio/issues/470
- Purpose
- Test

doc; update LB and FE component descriptions

---

docs/observability/readme.md
pkg/metrics/server.go

Remove TLS on metrics server
- Purpose
- Test

Expose metrics on HTTP

---

docs/components/frontend.md
docs/components/ipam.md
docs/components/nsp.md
docs/components/operator.md
docs/components/proxy.md
docs/components/stateless-lb.md
docs/components/tapa.md
docs/trouble-shooting/README.md

Documentation for debug-cli

---

pkg/ambassador/tap/conduit/conduit.go
pkg/nsm/interfacename/common.go

If state of connection received from monitoring is down indicating control plane issues, then request reselect to recover.
TAPA will still pass the old interface name in MechanismPreferences which the custom interfacename chain element must consider.
Without the reselect request in the above case the request would fail had and old control plane path segment been replaced.
And the request would only succeed after several minutes seemingly.
Testing:
- Deploy a fully functional trench and a target-example chart
- Abruptly terminate the tapa processes (e.g. using kill -9). Remember that example target won't re-open streams upon tapa cotainer restart.
- Delete some of the proxy PODs or forwarder PODs the example target PODs are connected to or are involved
- Manually open the streams again in …

TAPA; Check conn state received from monitoring

---

cmd/proxy/internal/client/fullmesh.go

Keep track of LB endpoints for their expiration time, and periodically check if any of them have expired after each return of reading a Find stream. Expired endpoints are evicted to terminate connections for unavailable endpoints.
#537 
- Purpose
- Test

proxy; LB endpoints evicted when expired

---

cmd/proxy/internal/client/fullmesh.go

Despite no control plane issue is indicated in case of recovered NSM connection towards a stateless-lb, still request reselect to force interface replacement. Thus, avoiding invalid neighbor cache entries to linger on in the stateless-lb.
An example for such invalid entries would be TAPA
related destinations where the MAC address would be updated after a proxy process crash (because of NSM heal with reselect due to the lack of datapath monitoring between TAPA and proxy).
#542 
- Purpose
- Test

proxy; request reselect during LB conn recover

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.1.5 (Documentation)

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.1.6 (Documentation)

---

pkg/kernel/monitor.go
pkg/loadbalancer/stream/loadbalancer.go

Fix deadlock between stream deletion interfaceMonitor.Unsubscribe call and interfaceMonitor.InterfaceCreated/InterfaceDeleted events.
Also, in processPendingTargets() update of Forwarding Availability is delayed until retryPendingTargets() has finished before reporting if the Stream had initial Targets yet ended up with no Targets. This could help avoid unnecessary signalling towards the Frontend, e.g. in case links get replaced in short time.
#562 
- Purpose
- Test

lb; prevent deadlock during stream deletion

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.1.7 (Documentation)

---

pkg/ipam/prefix/allocate_test.go

Test runs revealed flakiness in the old model's IPv4/IPv6 SQLite storage collision tests.
The concurrent add/delete churn, combined with the database intentionally lacking a CIDR uniqueness constraint, resulted in non-deterministic outcomes. Occasionally, a child would still achieve a stable allocation despite race conditions and collisions, causing previous exact assertions to fail.
The tests are now stabilized by asserting that not all children are expected to end up with a stable allocation, better reflecting the expected behavior under contention and no database-level uniqueness guarantee.
#569
- Purpose
- Test

ipam/test; Stabilize old SQLite model non-unique constraint tests

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.2.1 (Documentation)

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.2.3 (Documentation)

---

test/e2e/environment/kind-operator/test-scope.yaml
website/src/pages/versions.md

Release v1.2.4 (Documentation)
