deployments/helm/templates/_helpers.tpl
deployments/helm/templates/config.yaml
deployments/helm/templates/proxy.yaml
deployments/helm/values.yaml
examples/target/helm/templates/target.yaml
examples/target/helm/values.yaml

Support of the new configmap version
Fix: network service name in target helm chart
Unsed VIPs in proxy helm chart removed

New configmap version support in helm chart

---

cmd/frontend/service.go
docs/demo/xcluster.md
go.mod
go.sum

The configmap can hold Gateway specific BGP details
(e.g. ASN, ports, holdtime), that must be read by the
frontend to generate proper BGP config for BIRD.

frontend; process BGP params in configmap

---

cmd/frontend/service.go
cmd/proxy/main.go

Added refresh NetworkServiceClient chain element to proxy
NSC, thus the connection gets automatically renewed before
it would expire.

proxy; NSC connection to LB is renewed

---

api/target/target.proto
docs/demo/deployments/nsm-vlan/templates/forwarder-vlan.yaml
pkg/loadbalancer/loadbalancer.go
pkg/target/conduit.go

- Ambassador API documentation 
- The label forwarder was missing in the target request.
- The kernel forwarder in the NSM helm chart has been renamed to forwarder-vlan
- Fix nfqlb index:
- The minimum value of the index in nfqlb is 0 (instead of 1) and the maximum is 99 (instead of 100).
- The identifier is now equal to the index - 1 (index in nfqlb). The fwmark and identifer have not changed, the min is still 1 and the max 100.

Ambassador API documentation + vlan forwarder fix

---

build/load-balancer/Dockerfile
cmd/load-balancer/main.go
pkg/loadbalancer/stream/defrag.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/loadbalancer/types/consts.go

-Load kernel's IP defragmentation via conntrack allowing Flow rules
to match L4 information (e.g. ports).
-Do not allow defragmentation of IP packets arriving from the direction
of targets. Thus outbound IPv4 packets leaving the LB could keep their
originating source's "PMTU information".
-Forbid conntrack to do "book-keeping" in order to not "litter" memory.

lb; enable IP defrag to support Stream/Flow selection

---

pkg/nsp/registry/sqlite/sqlite.go
pkg/target/conduit/conduit.go

Fix Delete in SQLite storage of NSP:
The previous delete method (gorm) used was returning an error
The error was not returned by the target ambassador
Fix Target ambassador disconnect:
A wrong context was used to create the Network service client
The target could not disconnect from the proxy (context cancelled)

Fix target ambassador close and disconnect

---

docs/demo/deployments/xcluster/ovl/forwarder-test/default/bin/forwarder-test_test
docs/demo/deployments/xcluster/ovl/forwarder-test/forwarder-test.sh

Test connects timed out and caused seemingly random test failures. Turned out to be saturated conntrack tables.
* Set conntrack table size to 20000
* Do `conntrack -F` on the test-generator before mconnect

ovl/forwarder-test; Conntrack handling added

---

cmd/frontend/internal/bird/bird.go
cmd/frontend/internal/frontend/service.go
cmd/frontend/main.go

Shut down BIRD upon FE termination to allow configured protocol sessions graceful termination.
(Thus for example to allow BGP sessions to inform connected peers about their upcoming disappearance.)

fe; graceful BIRD shutdown

---

pkg/health/probe/probe.go

Increased connect and rpc timeouts of internal grpc-health-probes, so that containers running with lower CPU resources won't experience unnecessary probing failures.

probing; increase connect and rpc timeouts of internal gRPC probes

---

pkg/retry/config.go
pkg/retry/option.go
pkg/retry/retry.go
pkg/retry/retry_test.go

To cast a time channel to struct channel, a new go routine is created. A select with a new ctx has been added to cancel the retry trigger if the retry function is cancelled.

Fix go routine leak with retry trigger

---

pkg/kernel/interface.go

After the proxy restarts, it was trying to re-add existing IPs to the bridge but an error was raised by netlink since the IP was already existing.

Fix proxy bridge IP error after restart

---

pkg/ambassador/tap/conduit/manager_test.go

The delay to retry to open after an error received is hardcoded to 50ms. And the const timeout value for the open was set to 50ms, so the Test_Manager_Retry_Open test function could not always pass.

Fix TAPA unit test

---

cmd/proxy/internal/config/config.go
cmd/proxy/internal/service/client.go
cmd/proxy/internal/service/server.go
cmd/proxy/main.go
deployments/helm/templates/proxy.yaml
pkg/endpoint/config.go
pkg/nsm/mtu/client.go
pkg/nsm/mtu/server.go

Proxy as a center of TAPA-Proxy and Proxy-LB xconnects
changes Network Service Requests by adding MTU (retrieved
through environment variable).
This approach does not require additional privileges on the TAPA side.
(Also, on the Operator side similarly to Resource Management by implementing a dedicated annotation the MTU value could be set through Conduit CR.)

proxy; align Conduit MTU

---

cmd/proxy/internal/service/client.go
pkg/kernel/fwmark.go
pkg/nsm/fullmeshtracker/client.go

If the LB restarts, the rules and routes will remain in pod. So, before adding a target rule and route, the previous one are now removed.
New chain element for the full mesh client tracking the connection and the associated NSE name. So, if the connection has a problem (e.g. NSE Crash), NSM will set the connection to the same NSE and won't try to find a new one.
TODO: remove NSE from the map when they are removed (real close). This could be done using the NSM registry with the find function to remove the no longer existing NSEs from the map.
Issue: #225

Fix Load-balancer resiliency

---

cmd/frontend/internal/frontend/notify.go
cmd/frontend/internal/frontend/service.go
pkg/proxy/health/client.go

Due to the recently introduced KeepAlive mechanism for NSP Target registry
the periodic refresh (to announce FE availibilty) lead to excess logging.

fe; decreased log level of announcing fe service to nsp

---

build/ctraffic/Dockerfile
deployments/helm/templates/config.yaml
docs/demo/scripts/kind/Dockerfile
examples/target/helm/templates/target.yaml

[mconnect](https://github.com/Nordix/mconnect) and [ctraffic](https://github.com/Nordix/ctraffic) will now be available in the target and in the Kind GW/TG
ctraffic is listen on:
- TCP:
- 5000
- 5001
- 5002
- UDP:
- 5003
- 5004
mconnect is listen on:
- TCP:
- 4000
- 4001
- 4002
- UDP:
- 4003
- 4004
/
- Purpose
- Test

mconnect in target example container and GW/TG

---

.gitignore
Makefile
build/base/Dockerfile
build/ctraffic/Dockerfile
build/debug/Dockerfile
build/frontend/Dockerfile
build/ipam/Dockerfile
build/load-balancer/Dockerfile
build/nsp/Dockerfile
build/proxy/Dockerfile
build/tapa/Dockerfile
hack/build.sh
hack/host-build/Dockerfile.default
hack/host-build/Dockerfile.frontend
hack/host-build/Dockerfile.load-balancer

Use [Alpine Linux](https://www.alpinelinux.org/) as base for Meridio images.
Before Ubuntu 21 was used for most images, which is unnecessary fat and is not LTS. Build on a standardized base simplifies handling and a possible switch to a distroless image later on.
The image used as base for all Meridio images may look something like;
```
FROM alpine:3.15
RUN apk update && apk add iproute2
ADD https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.2/grpc_health_probe-linux-amd64 /bin/grpc_health_probe
RUN chmod a+x /bin/grpc_health_probe
```
A Meridio "debug" image will be created that can be loaded as a K8s [ephemeral container](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/). It will contain necessary debug tools.

Base image Alpine

---

build/base/Dockerfile
build/ctraffic/Dockerfile
build/debug/Dockerfile
build/frontend/Dockerfile
build/ipam/Dockerfile
build/load-balancer/Dockerfile
build/nsp/Dockerfile
build/proxy/Dockerfile
build/tapa/Dockerfile
cmd/tapa/main.go
deployments/helm/templates/ipam.yaml
deployments/helm/templates/load-balancer.yaml
deployments/helm/templates/nsp.yaml
deployments/helm/templates/proxy.yaml
deployments/helm/values.yaml
docs/front-end.md
docs/load-balancer.md
docs/proxy.md
docs/tapa.md
docs/user-application.md
examples/target/helm/templates/target.yaml
examples/target/helm/values.yaml

- Purpose
- Test
Meridio images now contain a numeric user that a container will be started with by default. Use "runAsUser: 0" to keep running as root.
- [] No
Deployment templates are modified to provide the required securityContext (runAsNonRoot and capabilities)

Non root user

---

build/debug/Dockerfile
build/load-balancer/Dockerfile

Nftables user space tool was missing from load-balancer image.
NA
- Purpose
- [x ] Bug fix
- Test
- [ x] Tested manually
- [ x] No
- [ x] No

lb; add nftables to image

---

deployments/helm/templates/load-balancer.yaml
deployments/helm/templates/nse-vlan.yaml
deployments/helm/values.yaml

VLAN NSE does not require any changes or capabilities to run as non-root.
NSC requires CAP_DAC_OVERRIDE to write to nsm-sock, and optionally CAP_NET_RAW
to use ping from the container.
The Dockerfile has been changed accordingly: https://github.com/Nordix/nsm-cmd-nsc/tree/privileges
https://github.com/Nordix/Meridio/issues/15
- Purpose
- Test
Respective template yaml files must be updated.

Run VLAN NSE,NSC as non-root

---

build/ctraffic/Dockerfile

* base image set to ubuntu 22.04
* tcpdump path changed
- Purpose
- Test

ctraffic image updated to 22.04

---

deployments/helm/templates/load-balancer.yaml

The NSC image without DNS is also available thanks to @uablrek: registry.nordix.org/cloud-native/nsm/cmd-nsc:v1.5.0-nodns
- Purpose
- Test

NSC DNS set to 127.0.0.1:10053

---

docs/demo/scripts/kind/bird/bird-gw.conf
docs/demo/scripts/kind/external-host.sh

* 3 VLANs per GW/TG
* trench-a: 100, 101, 102
* trench-b: 200, 201, 202
* trench-c: 300, 301, 302
* vlan0: `169.254.100.150/24`, `100:100::150/64`
* vlan1: `169.254.101.150/24`, `100:101::150/64`
* vlan2: `169.254.102.150/24`, `100:102::150/64`
* BGP conf to accept any interface
* New prompt
/
- Purpose
- Test

Improved TG/GW for Kind

---

cmd/frontend/internal/config/config.go
cmd/frontend/internal/frontend/service.go
cmd/frontend/main.go
cmd/ipam/main.go
cmd/load-balancer/main.go
cmd/nsp/main.go
cmd/proxy/main.go
deployments/helm/values.yaml
pkg/health/connection/connection.go
pkg/health/const.go
pkg/ipam/server.go
pkg/ipam/trench/watcher.go
pkg/nsm/client.go

Allow monitoring gRPC connection state changes e.g for IPAM and NSP clients, and adjust probe state respectively through context.
This might help in detecting connectivity issues affecting NSP or IPAM services.
The monitoring is lightweight meaning it works solely on the gRPC connection state maintained locally by the grpc pkg, no network traffic is involved. (Some grpc API functions marked as experimental were used, which might change in the future.)
#245 
- Purpose
- Test
Readiness probe update for IPAM.
- [] No

Monitor NSP and IPAM client connection state changes

---

build/frontend/Dockerfile
deployments/helm/templates/load-balancer.yaml
docs/front-end.md

Capability CAP_NET_RAW applied to bird binary in frontend image.
Said capability is required by Bird to use SO_BINDTODEVICE socket option when running as non-root.
https://github.com/Nordix/Meridio/issues/271
- Purpose
- Test
In our case the Operator already passes NET_RAW capability because of some debug tools.

fe; BIRD needs CAP_NET_RAW to use SO_BINDTODEVICE

---

deployments/helm/templates/nse-vlan.yaml

This hostport is not needed. If we have it, it will limit the number of trench we could have in a kubernetes. The max number of trench will be equal to the number of kubernetes worker node.
/
- Purpose
- Test

Remove hostport from the NSE-VLAN container

---

pkg/log/logger.go
pkg/log/logger_test.go

When testing https://github.com/networkservicemesh/sdk/pull/1348 with the `NSMLogger` an un-initiated Sugar logger (the `s` field) caused a segv. This PR initiates the field and adds a unit-test that would segv without it.
- Purpose
- Test

Fix a segv in NSMLogger.WithFields()

---

pkg/log/logger.go

The logs were directed to stderr, but should go to stdout.
Test with `go test` redirects stderr to stdout which is a lesson to learn for future testing.
#253
- Purpose
- Test

Structured logging; logs to stdout

---

Makefile
build/base-image/Dockerfile

* Update grpc health probe binary in base image
* Makefile silent make command
* Add Grype, Trivy and Nancy as security scanner tool
CVEs:
CVE-2022-27191 // grpc_health_probe
CVE-2015-5237  // false-positive (protobuf) - https://github.com/anchore/grype/issues/558
CVE-2021-33194 // grpc_health_probe
CVE-2022-33082 // Will be fixed in NSM 1.6
CVE-2021-44716 // from ctraffic and mconnect + grpc_health_probe
CVE-2022-28946 // Will be fixed in NSM 1.6
CVE-2021-22570 // false-positive (protobuf) - https://github.com/anchore/grype/issues/558
CVE-2021-38561 // grpc_health_probe
New Makefile commands:
```
make grype
make trivy
make nancy
```
/
- Purpose
- Test

Add Security scan tools + fix CVEs

---

deployments/helm/templates/nse-vlan.yaml

Remove nsm-sock hostPath volume from Remote VLAN NSE. It does not need to contact NSMgr, instead
communicates with NSM registry.
NA
- Purpose
- Test
Respective template must be updated to remove the hostPath.

deployment; remote vlan nse does not need to communicate with NSMgr

---

build/base-image/Dockerfile
go.mod
go.sum

GRPC-Health-Probe still need to be fixed:
https://github.com/grpc-ecosystem/grpc-health-probe/pull/124
/
- Purpose
- Test

Update golang.org/x/net to fix CVE-2022-27664

---

build/stateless-lb/Dockerfile

The fix for ref-counters in nfqlb-1.1.2 was too simplistic and causes a short break when the flow doesn't exist on update, because of the delete/re-create approach.
nfqlb-1.1.3 also includes a fix for a similar problem when the flow "target" (which is the load-balancer/stream in Meridio).
https://github.com/Nordix/nfqueue-loadbalancer/issues/12
- Purpose
- Test

Upgrade to nfqlb-1.1.3

---

Makefile
docs/demo/scripts/kind/Makefile

Fix ginkgo and kind binary path in Makefiles
https://jenkins.nordix.org/blue/organizations/jenkins/meridio-e2e-test-kind/activity
/
- Purpose
- Test

Fix ginkgo and kind binary path in Makefiles

---

docs/demo/scripts/kind/Makefile

Add missing kind-delete-cluster pre-target
/
- Purpose
- Test

Add missing kind-delete-cluster pre-target

---

docs/test.md

The tests are now running in the CI:
https://jenkins.nordix.org/blue/organizations/jenkins/meridio-e2e-test-kind/activity/
This PR adds the badges in the documentation reporting the 1000 latest e2e test runs. 
[![meridio-e2e-kind-meridio](https://jenkins.nordix.org/job/meridio-e2e-test-kind/lastCompletedBuild/badge/icon?config=meridio-e2e-kind-meridio)](https://jenkins.nordix.org/job/meridio-e2e-test-kind/lastCompletedBuild)
[![meridio-e2e-kind-tapa](https://jenkins.nordix.org/job/meridio-e2e-test-kind/lastCompletedBuild/badge/icon?config=meridio-e2e-kind-tapa)](https://jenkins.nordix.org/job/meridio-e2e-test-kind/lastCompletedBuild)
[![meridio-e2e-kind-nsm](https://jenkins.nordix.org/job/meridio-e2e-test-kind/lastCompletedBuild/badge/icon?config=meridio-e2e-kind-nsm)](https://jenkins.nord …

Add E2E tests badges

---

test/e2e/environment/kind-helm/Makefile
test/e2e/environment/kind-helm/test-scope.yaml

This Makefile deploys the Meridio environment needed to run the e2e tests using kind and Helm. The CI will now have the environment (kind-helm) as parameter, so it will be possible to run any other environment (like the kind + operator).
Enables NSM 1.5.0 and disable ipv4/ipv6 e2e tests.
https://gerrit.nordix.org/c/infra/cicd/+/15875
- Purpose
- Test

CI: New Makefile for kind-helm e2e environment

---

readme.md

- Update Build badge with new periodic job
- Add CVE badge with new security scanner job
- Report can be found in the artifacts of the runs (report.txt)
CVE report for the first run: https://jenkins.nordix.org/job/meridio-periodic-security-scan/lastSuccessfulBuild/artifact/_output/report.txt
/
- Purpose
- Test

Build and CVE bagde in the readme

---

api/v1alpha1/gateway_types.go
config/crd/bases/meridio.nordix.org_gateways.yaml

Name of the kubernetes Secret containing the password must be a valid lowercase RFC 1123 subdomain.
`a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`
https://github.com/Nordix/Meridio/issues/329
- Purpose
- Test
Gateway CRD validation.

Fix validation of BGP auth related CRD parameters

---

pkg/kernel/fwmark.go
test/e2e/utils/trafficgenerator.go

If a target is disconnecting and connecting again to a conduit on a short period, the IP(s) allocated to the target might be the same, but the MAC address will be different. The LBs will still have the old IP(s)-MAC address association in the neighbor table, it then has to be cleaned, traffic towards that target will be lost until the time for the cache to be automatically removed.
This fix solves most of the failing e2e caused by: https://github.com/Nordix/Meridio/issues/234
Based on the latest 130 runs, we have now 13% of failing runs (30% without the fix).
1. Currently the neighbor entry for a target is cleaned no matter if the target is already configured for another stream or not. This means some traffic can go through stream-a (target-1 has opened it), and a target-1 opens stream-b, …

Clean target IP from Neighbor table on add

---

docs/demo/scripts/kind/Makefile

The NSM version was not used in the kind environment makefile.
https://github.com/Nordix/Meridio/issues/318
- Purpose
- Test

e2e kind env set the NSM version

---

Makefile
build/init/Dockerfile
deployments/helm/templates/load-balancer.yaml
deployments/helm/templates/proxy.yaml
deployments/helm/values.yaml
hack/build.sh
hack/meridio-init.sh

An initContainer is used to set sysctl's in the load-balancer and proxy PODs. It is currently a BusyBox image, not related to any other Meridio image. This PR adds an init image based on the Meridio base image (same as all other Meridio images).
The initContainer will get more responsibilities in the future, e.g. to setup a tunnel device in test environments that have no secondary networks, like public-cloud and "standard" test clusters. Therefore a `meridio-init.sh` is included for now, but more advanced programs can be added if necessary.
The first commit in this PR only builds and uses the new init image. The start commands (a bunch of sysctl -w) is not altered. However the `meridio-init.sh` is prepared to handle start without parameters.
```yaml
initContainers:
- name: init
image: …
```

Add a Meridio adapted initContainer image

---

cmd/frontend/main.go
cmd/proxy/main.go
cmd/stateless-lb/main.go
cmd/tapa/main.go

In NSM v1.7.x the NSM logger can be configured to use structured logging. This PR ensures that structured logging is used even for NSM trace logging.
The NSM trace logging uses a format with indentations that is awkward when structured logging is used. A better way would be to post-process log entries whic is made simple by structured logging.
- Purpose
- Test

Use structured logging on TRACE level

---

docs/test.md
pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go
pkg/ambassador/tap/trench/trench.go
pkg/nsm/ipcontext/client.go
pkg/nsm/ipcontext/common.go
pkg/nsm/ipcontext/server.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
test/e2e/environment/kind-operator/dualstack/test.sh
test/e2e/trench_test.go

- Allow internal target IP change without close/reopen
- When a trench/conduit/stream is deleted and recreated, the target that was connected will again request the connections with the old parameters (IPs, GWs, routes...). The proxy might get different subnets allocated and will forget the target IPs in use. So this will cause the targets to have wrong/colliding IP addresses.
- The proxy is now detecting if a target is requesting the connection with invalid IP addresses and will fix them together with the other parameters (GWs, routes...).
- In addition, the tapa can now handle the internal IP changes and will register itself with the new IP assigned.
- Fix NSP reconnect in the TAPA in case of NSP service delete/create  
- If the NSP service is re-created, the TAPA will take around 15 …

Allow internal target IP change without close/reopen

---

cmd/tapa/main.go
pkg/ambassador/tap/trench/trench.go

Fixed TAPA termination so that open streams could be properly closed to avoid lingering interfaces on the proxy side.
A call to wg.Done() was also missing  in disconnectConduits() ambassador/tap/trench/trench.go causing tear-down to get stuck.
Test:
1., Deploy a trench and example targets connected to a stream in previous trench.
2., Check the interfaces with prefix in the proxies (proxies serve target PODs running on the same worker).
The interfaces connecting proxy with target PODs have prefix `proxy.load-` assuming NSM_SERVICE_NAME is `proxy.load-balancer.[TRENCH_NAME]`.
3., Remove the example target deployment (or scale-in the number of PODs or simply kill a target POD). The related interfaces in proxies must disappear with the changes. Basically, the number of such interfaces in the …

tapa; graceful shutdown

---

cmd/frontend/internal/bird/bird.go
cmd/frontend/internal/bird/proto.go
cmd/frontend/internal/bird/static_test.go
cmd/frontend/internal/frontend/service.go

BIRD removes a BFD session if the net devive hosting it becomes unavailable.
This might be misleading, as the status printouts won't indicate any of that, while the related gateway will be considered down.
To ease troubleshooting that information is included from now on.
example (including the changes):
```
{
"severity": "error",
"timestamp": "2023-01-27T15:12:42.81+00:00",
"service_id": "Meridio-frontend",
"message": "connectivity",
"version": "1.0.0",
"extra_data": {
"class": "FrontEndService",
"func": "Monitor",
"status": 18,
"out": [
"BIRD 2.0.8 ready.",
"Name       Proto      Table      State  Since         Info",
"NBR-gateway1 Static     master4    up     15:09:08.239   bfd: no session",
"NBR-gateway2 Static     master6    up     15:09:08.239   bfd: no session",
""
],
"error": …
```

frontend; lack of bfd session logged for gateways with static+bfd

---

pkg/nsp/registry/sqlite/sqlite.go
pkg/nsp/registry/sqlite/sqlite_test.go

When a stream was switched between 2 different conduits (switched or deleted/created in a new conduit), the NSP sqlite registry was taking the old conduit association instead of updating the conduit name of the association.
This case is covered by the e2e test: `new-stream` followed with `new-attractor-nsm-vlan` 
To reproduce the bug:
1. Create a stream (S-1) in a conduit (C-1)
2. Open the stream (S-1) in a target
3. Move the stream (S-1) in conduit (C-2) 
4. Open the stream (S-1) in a target
Due to the missing `FullSaveAssociations` in gorm setting, and the previous registration of a Target in S-1.C-1, when the stream will be moved, the NSP will register new targets with S-1.C-2 without updating the nested conduit property C-1 to C-2.
This will cause the NSP to return an empty list of …

Fix NSP Target Registry on stream conduit switch

---

api/v1/stream_webhook.go

Mistakenly the pointer values and not the contents of max-targets pointers were compared by the stream webhook.
The faulty check lead to strange problems such as a Stream could not be removed properly (got stuck in the config map unless the related Flows were removed previously).
NA
- Purpose
- Test
Stream webhook fixed.

operator; fix max-targets validation for Streams

---

config/templates/charts/meridio/deployment/ipam.yaml
config/templates/charts/meridio/deployment/nsp.yaml
deployments/helm/templates/ipam.yaml
deployments/helm/templates/nsp.yaml

Set persistentVolumeClaimRetentionPolicy for NSP and IPAM statefulsets.
The retention behaviour orders PVC deletion when the related statefulset is deleted. Thus old persistent databases won't be retained when a trench gets redeployed, and won't interfere with subsequent Trench deployments.
Note: requires k8s feature gate **StatefulSetAutoDeletePVC**
https://github.com/Nordix/Meridio/issues/361
- Purpose
- Test

Set persistentVolumeClaimRetentionPolicy for NSP and IPAM statefulsets

---

pkg/ipam/conduit/conduit.go
pkg/ipam/conduit/conduit_test.go
pkg/ipam/trench/trench_test.go
pkg/proxy/proxy.go

* The proxy was not releasing the dst IPs
* Fix node subnet allocation which was not returning error on Full conduit subnet
https://github.com/Nordix/Meridio/issues/366
- Purpose
- Test

Fix IP release on proxy and fix Node subnet allocation

---

website/docusaurus.config.js
website/src/pages/markdown-page.md
website/src/pages/training.md

Add new section of the website for the training materials.
https://website.meridio.pages.dev/training
https://github.com/Nordix/Meridio/issues/365
- Purpose
- Test

Add training page on website

---

Makefile
pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go
pkg/ambassador/tap/conduit/manager.go
pkg/ambassador/tap/conduit/manager_test.go
pkg/ambassador/tap/trench/conduit.go
pkg/ambassador/tap/trench/configuration.go
pkg/ambassador/tap/trench/trench.go
pkg/ambassador/tap/trench/trench_test.go
pkg/ambassador/tap/types/conduit.go
pkg/ambassador/tap/types/mocks/conduit.go
test/utils/utils.go
test/utils/waitgroup.go

- TAPA: Stream retry delay configurable
- The delay was 50ms before, even in the unit tests. It is now 1 second by default and 1ms in the unit tests.
- TAPA: fix concurrency issue in the stream retry
- if multiple events occur (AddStream, SetStreams), a stack of Open would pile up waiting for the mutex to be unlocked. When the mutex would be unlocked (on close call), the close could then be executed, and after, piled open calls would execute again, which would cause the stream to be re-opened.
- TAPA: fix conduit SetVips
- SetVips could be called even after the conduit has been disconnected. So the NSM connection would have been requested a new time and the interface would be remaining in the pod.
https://github.com/Nordix/Meridio/issues/316
https://github.com/Nordix/Meridio/pull/343 …

Fix TAPA concurrency issue

---

cmd/tapa/main.go
pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go
pkg/ambassador/tap/tap.go
pkg/ambassador/tap/trench/factory.go
pkg/ambassador/tap/trench/trench.go

The conduit handler in the TAPA is now monitoring the NSM connection to get the local IPs up to date. The local IPs can be updated by the proxy in case of a restart.
grpcKeepaliveTime has been increased to avoid grpc err: ENHANCE_YOUR_CALM:too_many_pings
https://github.com/Nordix/Meridio/issues/383
https://github.com/Nordix/Meridio/issues/159
- Purpose
- Test

Monitor NSM connection in TAPA to get latest local IPs 

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

TAPA connection IPs are stored in IPAM using TAPA side ID as key (i.e. the first segment path ID of NSM connection).
The goal is to make the IPs associated with a TAPA NSM connection retrievable even if the collocated Proxy POD is replaced (e.g. due to upgrade).
As a consequence the IPs for such NSM connection do not need to be replaced after the Proxy POD changes. Thus for example the old Proxy POD IP of the connection is not leaked either.
https://github.com/Nordix/Meridio/issues/386
- Purpose
- Test
- [ x Tested manually
TAPA connections that has been up before upgrading the Proxy will get a new IP. It has been agreed that this NBC is acceptable. The effects of the NBC are the same described in https://github.com/Nordix/Meridio/issues/383, and old IPs will …

proxy; TAPA connection IPs stored in IPAM using TAPA side ID as key

---

pkg/loadbalancer/stream/loadbalancer.go
pkg/loadbalancer/stream/target.go

Log contents of interface objects instead of the object itself in structured logging.
After a bit of fumbling I realized the right way is to define a custom `MarshalJSON` function for the _real_ class. Example:
```go
func (t *Target) MarshalJSON() ([]byte, error) {
ts := struct {
Identifier int      `json:"identifier"`
IPs        []string `json:"ips"`
}{
t.getIdentifier(),
t.nspTarget.GetIps(),
}
return json.Marshal(&ts)
}
```
#358
- Purpose
- Test

Log contents of interface objects

---

cmd/proxy/internal/client/fullmesh.go
pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go

Due to the implementation of the NSM monitor connections in the TAPA, the split between local IPs and VIP addresses was not good enough, so the TAPA was registering itself with some VIP + local IPs.
https://github.com/Nordix/Meridio/pull/387
- Purpose
- Test

Fix VIPs used as local IPs in TAPA

---

build/base-image/Dockerfile

Update google.golang.org/protobuf to v1.30.0.
https://github.com/grpc-ecosystem/grpc-health-probe has to be fixed: https://github.com/grpc-ecosystem/grpc-health-probe/pull/138 (Waiting for a release).
https://jenkins.nordix.org/job/meridio-periodic-security-scan/180/artifact/_output/report.txt
https://github.com/advisories/GHSA-hw7c-3rfg-p46j
- Purpose
- Test

Fix CVE-2023-24535

---

cmd/stateless-lb/main.go
pkg/kernel/interface.go

When a new interface is detected any existing interface with the same subnet is disabled
https://github.com/Nordix/Meridio/issues/392
- Purpose
- Test

Stateless-lb: Disable old interfaces with same subnet as new

---

cmd/frontend/internal/env/config.go
cmd/frontend/main.go
cmd/ipam/config.go
cmd/ipam/main.go
cmd/proxy/internal/config/config.go
cmd/proxy/main.go
cmd/stateless-lb/config.go
cmd/stateless-lb/main.go

Add keepalive setting for grpc connections towards NSP and IPAM improving the time for connection to be re-established after a failure.
https://www.evanjones.ca/tcp-connection-timeouts.html
https://github.com/Nordix/Meridio/issues/355
- Purpose
- Test

Keepalive on grpc connections

---

cmd/frontend/internal/env/config.go
cmd/frontend/internal/frontend/notify.go
cmd/frontend/internal/frontend/service.go

There seems to be a bug in here somewhere. But I couldn't follow all logic so I made a general cleanup.
One thing that might have been a bug is the "break" in
https://github.com/Nordix/Meridio/blob/60a45b5a8254ada9843466871abccc62eb9f1f30/cmd/frontend/internal/frontend/service.go#L314
The Monitor can exit more or less silently and announceFe will not be called in intervals ever after.
May fix the NSP-FE issue described in https://github.com/Nordix/Meridio/issues/355#issuecomment-1514477574
- Purpose
- Test

Frontend: Cleanup Monitor() function

---

pkg/log/logger.go

The "Sample" function in the zap logger is enabled by default. We are not using it, and it consumes a lot of memory, ~>50%~ 20-30% of heap mem in TAPA for instance.
- Purpose
- Test

Log: disable the Sample function

---

cmd/ipam/config.go
cmd/ipam/main.go
cmd/proxy/internal/config/config.go
cmd/proxy/main.go
cmd/stateless-lb/config.go
cmd/stateless-lb/main.go
config/operator/operator.yaml
config/templates/charts/meridio/deployment/ipam.yaml
config/templates/charts/meridio/deployment/nse-vlan.yaml
config/templates/charts/meridio/deployment/nsp.yaml
config/templates/charts/meridio/deployment/proxy.yaml
config/templates/charts/meridio/deployment/stateless-lb-frontend.yaml
deployments/helm/templates/_helpers.tpl
pkg/controllers/attractor/stateless-lb-frontend.go
pkg/controllers/common/const.go
pkg/controllers/conduit/proxy.go
pkg/controllers/trench/ipam.go
pkg/health/probe/probe.go

Using SPIFFE Workload API to retrieve TLS credentials can be CPU intensive. Thus, employing resource limits for Spire can lead to failed probes.
Set default rpc-timeout of grpc-health-probes in case of SPIFFE issued credentials to 1s.
Also, use 2 seconds initial delay for liveness probes not to overlap with readiness probes.
RPC timeout of code internal grpc-health-probes can be adjusted via `GRPC_PROBE_RPC_TIMEOUT` operator environment variable (expects time.Duration values).
https://github.com/Nordix/Meridio/issues/420
- Purpose
- Test

Adjust rpc-timeout of gRPC probes

---

pkg/retry/retry.go

Using the retry pkg, if the retry iterates many times (maybe infinitly), the errFinal will increase and will consume more and more memory. For now, only the latest error will then be returned.
/
- Purpose
- Test

Retry: return only last error

---

cmd/stateless-lb/main.go

LB-FE keeps track of interfaces connecting it with proxies. When a proxy interface is replaced, the old interface might linger on, or might not even get removed from the interface list. That's because LB-FE only gets InterfaceDeleted() event upon an NSM connection Close() request. Which might happen with severe delay (MaxTokenLifetime expiration), or might not even happen if the Close fails (does not reach LB-FE's interfacemonitor server chain). Either way, it leads to unnecessary and confusing excess work and printouts where LB-FE tries to set the old interface's state to Down again and again.
So let's remove the old interface from the interface list when the interface replace event is first noticed.
NA
- Purpose
- Test

LB; remove replaced interface from interfaces list

---

cmd/frontend/internal/bird/constants.go
cmd/frontend/internal/frontend/service.go
cmd/stateless-lb/egress.go

Advertise multi-protocol extension capability matching the associated Gateway's IP version,
Achieved by using separate BIRD BGP templates for IPv4, IPv6.
(Refer to the related issue for details.)
https://github.com/Nordix/Meridio/issues/370
- Purpose
- Test

FE; advertise single AFI/SAFI pair via BGP

---

pkg/nsm/client.go
pkg/nsm/endpoint/expirationtime/nse_client.go

With https://github.com/networkservicemesh/sdk/pull/1404 NSE expiration time is controlled by NSM's MaxTokenLifetime parameter. This token lifetime defaults to 10 minutes, resulting in 10 minutes NSE lifetimes.
Introduce a custom chain function to ensure LB/Proxy NSEs are registered using 1 minute lifetime like before.
https://github.com/Nordix/Meridio/issues/438
- Purpose
- Test

Retain legacy calculation of NSE expiration time

---

deployments/helm/templates/_helpers.tpl
docs/components/frontend.md
pkg/controllers/common/models.go

As per BIRD documentation, use ip_local_port_range to force BIRD using IANA approved src ports for BFD.
```BFD packets are sent with a dynamic source port number. Linux systems use by default a bit different dynamic port range than the IANA approved one (49152-65535). If you experience problems with compatibility, please adjust /proc/sys/net/ipv4/ip_local_port_range.```
NA
- Purpose
- Test

FE; make BIRD use IANA approved ports for BFD (49152-65535)

---

pkg/controllers/trench/configmap.go

The operator is reconciling the configmap all the time. It does that because it compares the desire state with the current state, but the changes between the states might only be ordering, so the configmap is applied again and again. And that triggers the NSP events which forwards the events to all other components (since we don't have cache) which cause high CPU usage.
The configmap content is now sorted, so the configmap is reconciled correctly.
- Purpose
- Test

Fix configmap reconciler

---

pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/conduit_test.go
pkg/nsm/interfacename/cache.go

TAPA uses a `deterministic` NSM Connection/Segment ID that does not change if connecting to [Conduit, Trench] tuple with the same names from the same application POD.
```
var nsName string = conduit.GetNetworkServiceNameWithProxy(c.Conduit.GetName(), c.Conduit.GetTrench().GetName(), c.Namespace)
var id string = fmt.Sprintf("%s-%s-%d", c.TargetName, nsName, 0)
```
In case NSM connection Close() fails for example on the TAPA side for some reason (or the TAPA container crashes), then requesting a new connection with the same Connection ID will create a second connection in NSM.
Unfortunately, once the "old" connection's token lifetime expires, and NSM orders clean-up, it will trigger a `heal event` in TAPA because of the shared Connection ID.
This will lead to unwanted NSM connection …

TAPA queries NSM to re-use connection if possible

---

pkg/ambassador/tap/conduit/conduit.go
pkg/nsm/interfacename/cache.go
pkg/nsm/interfacename/cache_test.go
pkg/nsm/interfacename/client_test.go
pkg/nsm/interfacename/common.go
pkg/nsm/interfacename/generator.go
pkg/nsm/interfacename/server_test.go

Related to https://github.com/Nordix/Meridio/pull/444
In case of a connection recovered through NSM's connection monitor, the so called interface name cache in interfaceNameClient could have become out of sync.
That's because the cache was not contacted in such cases, thus upon a faulty Close() or TAPA crash the cache failed to keep track of recovered names. (Which means, such names could be re-used by some other connection.)
Therefor, move the interface name of recovered connections from Mechanism to MechanismPreferences, so that intefaceNameClient could handle such connection requests properly.
If the inteface name is not yet taken by some other connection, then use it, and also update the inteface name cache if needed. (But generate a new name if already taken by another connection.)
- …

TAPA; sync interface name cache for recovered connections

---

cmd/frontend/internal/bird/bgp_test.go
cmd/frontend/internal/env/config.go
cmd/frontend/internal/frontend/service.go
docs/components/frontend.md
docs/demo/scripts/kind/Dockerfile
docs/demo/scripts/kind/bird/bird-common.conf
docs/demo/scripts/kind/bird/bird-gw-no-default.conf
docs/demo/scripts/kind/external-host.sh

- BIRD filters used by the generated BIRD configuration have been updated to accept non-default routes announced by connected BGP peers.
- Introduced new low prio PBR rule to ensure outbound VIP traffic is not misrouted, i.e. will not be leaked to primary network.
Blackhole logic is installed by default, but can be configured through frontend env variable DROP_IF_NO_PEER.
(The related blackhole routes are inserted by BIRD as well.)
- Updated external-host test tool to either announce default routes (default behavior), or advertise certain pre-defined network routes.
Start external-host to announce non-default routes:
./docs/demo/scripts/kind/external-host.sh --default-route=no
#453 
- Purpose
- Test

FE; BGP also accepts advertised non-default routes

---

config/operator/patches/operator_resource_templates_patch.yaml

Fix mount path of resource templates.
Since home dir has been changed in the image by some commit, the operator was unable to open the resource templates.
#458 
- Purpose
- Test

operator; fix mount path of resource templates

---

config/operator/operator.yaml
deployments/helm/templates/_helpers.tpl
docs/components/stateless-lb.md
pkg/controllers/common/const.go
pkg/controllers/common/models.go
pkg/controllers/conduit/proxy.go
pkg/loadbalancer/nfqlb/netfilter.go

In LB-FE make sure to return ICMP reply to external party from the VIP src the offending packet was sent to.
This is achieved by using nftables rules doing stateless SNAT on ICMP replies generated by the LB-FE.
Only replies triggered by incoming packets with VIP dst are of interest. (In which case MTU related ICMP reply can be triggered during forwarding of the original packet.)
Solution requires sysctl fwmark_reflect enabled for both ipv4 and ipv6:
- Helps limit scope of the introduced rules by checking if fwmark is non-zero.
- Inheriting the fwmark value of the original packet allows for an early successful route lookup due to the Target specific routes in place, thus the ICMP reply can be generated by the stack (instead of being discarded due to unreachable error). …

LB; improve PMTUd support for external clients

---

api/v1/gateway_types.go
config/crd/bases/meridio.nordix.org_gateways.yaml

In Gateway Custom Resource BGP port parameters default to 179.
It's not mandatory anymore to set these ports explicitly when defining a CR.
#405 
- Purpose
- Test

operator; BGP ports default to 179

---

cmd/stateless-lb/egress.go
cmd/stateless-lb/main.go
pkg/endpoint/endpoint.go
pkg/loadbalancer/nfqlb/nfqlb.go
pkg/loadbalancer/types/nfqlb.go
pkg/nsm/client.go

Due to a buried "Fatal" printout the LB failed to run all the clean-ups (e.g. NSE unregister) during shutdown.
NA
- Purpose
- Test

Lb; during shutdown run all clean-up

---

pkg/kernel/bridge.go
pkg/networking/mac.go

Setting the bridge mac address prevents the address changes when an interface is attached/detached. This caused issue when connecting targets and stateless-lbs to the proxy. The ARP table of other connected pods were not updated instantly.
https://github.com/Nordix/Meridio/issues/471
- Purpose
- Test

Set mac address of bridge0 in proxy

---

cmd/stateless-lb/main.go
docs/observability/dashboard.json
docs/observability/metrics.md
pkg/loadbalancer/stream/loadbalancer.go
pkg/loadbalancer/stream/target.go
pkg/loadbalancer/target/metrics.go
pkg/loadbalancer/types/target.go
pkg/metrics/const.go

Collect number of packets and bytes for each target. Metrics are collected based on nftables metrics on postrouting rules matching target identifier (fwmark).
Example of the new nftables table with 3 targets:
```
table inet meridio-metrics { # handle 1
chain target-hits { # handle 1
type filter hook postrouting priority -500; policy accept;
meta mark 0x000013c3 counter packets 255 bytes 13668 # handle 2
meta mark 0x000013d2 counter packets 310 bytes 16616 # handle 3
meta mark 0x000013da counter packets 260 bytes 13936 # handle 4
}
}
```
https://github.com/Nordix/Meridio/pull/428
https://github.com/Nordix/Meridio/issues/419
- Purpose
- Test

Target hits metrics

---

cmd/frontend/internal/env/config.go
cmd/frontend/main.go
cmd/stateless-lb/main.go
config/templates/charts/meridio/deployment/stateless-lb-frontend.yaml
docs/observability/dashboard.json
docs/observability/metrics.md
pkg/kernel/metrics.go
pkg/metrics/const.go
pkg/nsm/metrics/server.go

Collect kernel rx_packets, tx_packets, rx_bytes, tx_bytes, rx_errors, tx_errors, rx_dropped, tx_dropped metrics of the interfaces Stateless-lb collects the metrics for the interfaces being created via NSM. 
A new chain element has been implemented to watch/unwatch interfaces based on their name.
Frontend collects the metrics of the interface that is passed as environment variable.
https://github.com/Nordix/Meridio/pull/428
https://github.com/Nordix/Meridio/issues/419
- Purpose
- Test

Interface Metrics

---

cmd/ipam/main.go
cmd/nsp/config.go
cmd/nsp/main.go
cmd/proxy/main.go
cmd/stateless-lb/main.go
config/templates/charts/meridio/deployment/nsp.yaml
deployments/helm/values.yaml
docs/components/nsp.md
pkg/controllers/trench/nsp.go
pkg/health/checker.go
pkg/health/const.go
pkg/health/probe/option.go
pkg/health/probe/probe.go
pkg/nsp/registry/keepalive/keepalive.go

Refer to the related issue.
Kubernetes native grpc probes are not introduced, because it does not seem to support servers using unix sockets (hence grpc-health-probe binary cannot be removed from the images):
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#httpgetaction-v1-core
#474 
- Purpose
- Test

New internal gRPC health client instead of grpc-health-probe binary

---

cmd/frontend/internal/frontend/service.go
cmd/frontend/main.go
cmd/ipam/main.go
cmd/nsp/main.go
cmd/proxy/main.go
cmd/stateless-lb/main.go
cmd/tapa/config.go
cmd/tapa/main.go
config/templates/charts/meridio/deployment/ipam.yaml
config/templates/charts/meridio/deployment/nsp.yaml
config/templates/charts/meridio/deployment/proxy.yaml
config/templates/charts/meridio/deployment/stateless-lb-frontend.yaml
deployments/helm/values.yaml
docs/components/frontend.md
docs/components/ipam.md
docs/components/nsp.md
docs/components/proxy.md
docs/components/stateless-lb.md
docs/components/tapa.md
examples/target/deployments/helm/values.yaml
pkg/health/checker.go
pkg/health/const.go
pkg/health/probe/probe.go
pkg/health/wrapper.go
pkg/health/wrapper_test.go

- NSP, IPAM, Proxy and LB register _Liveness_ probe service at custom gRPC health server.
- FE no longer checks Target Registry Client as part of Readiness.
- IPAM, NSP Readiness no longer includes their server status.
- Liveness probes in IPAM, NSP, Proxy and LB containers rely on service name "Liveness" to check status.
- Health server in TAPA hosts health services _Liveness_, _Startup_ and _Readiness_ out of the box. Ambassador server availability is returned as part of Liveness. (Example-target has been updated accordingly.) Note, it's not mandatory to use these health services in the kubernetes probe configuration, but using them could avoid the need of revisiting the probe configuration in the TAPA container if the recommended probe setup changes (the implementation would change in …

Liveness probe with subservices

---

pkg/ambassador/tap/conduit/conduit.go
pkg/ambassador/tap/conduit/configuration.go
pkg/ambassador/tap/conduit/manager.go
pkg/ambassador/tap/conduit/manager_test.go
pkg/ambassador/tap/stream/stream.go
pkg/ambassador/tap/stream/stream_test.go
pkg/ambassador/tap/stream/targetregistry.go
pkg/ambassador/tap/tap.go
pkg/ambassador/tap/trench/conduit.go
pkg/ambassador/tap/trench/configuration.go
pkg/ambassador/tap/trench/factory.go
pkg/ambassador/tap/trench/trench.go
pkg/ambassador/tap/trench/trench_test.go
pkg/health/connection/connection.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/nsm/interfacename/cache.go
pkg/nsm/interfacename/client.go
pkg/nsm/interfacename/common.go

Improved logs to help troubleshooting (wrapped errors during return to help identify the error source during debugging etc.).
other improvements:
TAPA;
- stream: Do not try to unregister target at target registry
if stream has no identifier.
- stream: During open when identifier collision is observed,
release offending identifier by unregistering at target registry.
- conduit: Compare VIPs received from configuration, and trigger
NSM connection update upon change only.
- conduit: Log connection monitor events related to control plane
change and connection close for visibility.
- conduit: Log when IPs of a NSM connection change. And initiate
close and re-open of affected Streams through the stream manager.
- Custom interfacename client chain element releases interface name
during failed …

TAPA logs and other improvements

---

pkg/proxy/proxy.go

ipReleaser was not calling unlock on a return causing a deadlock in some cases.
- Purpose
- Test

Fix deadlock on UnsetIPContext

---

cmd/proxy/main.go
cmd/stateless-lb/egress.go
cmd/stateless-lb/main.go
pkg/endpoint/endpoint.go
pkg/kernel/fwmark.go
pkg/kernel/monitor.go
pkg/kernel/neighbor/monitor.go
pkg/kernel/neighbor/reachability.go
pkg/kernel/neighbor/types.go
pkg/loadbalancer/flow/flow.go
pkg/loadbalancer/flow/metrics.go
pkg/loadbalancer/nfqlb/netfilter.go
pkg/loadbalancer/nfqlb/nfqlb.go
pkg/loadbalancer/nfqlb/stats.go
pkg/loadbalancer/stream/defrag.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/loadbalancer/stream/target.go
pkg/loadbalancer/types/nfqlb.go
pkg/nsm/monitor/connection.go
pkg/utils/error.go

Improved logs to help troubleshooting.
other:
- Monitor NSM connections the LB is involved in for DELETE
and DOWN events for logging (functionality shared by lb and proxy)
- Stream lb instance unsubscribes at interface monitor on delete
- LB subscribes to native interface monitor to learn about
interface removal to sync its interface list
- Monitor Target reachability based on kernel neighbor events,
and log changes
NA
- Purpose
- Test

LB logging and some improvements

---

pkg/loadbalancer/flow/metrics.go

Error wrapping improvements in LB broke the flow metrics collecting feature by returning an error all the time.
N/A
- Purpose
- Test

metrics; fix collecting flow stats

---

cmd/frontend/internal/frontend/metrics.go
cmd/frontend/internal/frontend/metrics_test.go
cmd/frontend/internal/frontend/service.go
cmd/frontend/main.go
docs/observability/dashboard.json
docs/observability/metrics.md
pkg/metrics/const.go

Collect metrics of routes imported, exported and preferred for each gateways. The metrics are extracted and parsed from show protocol all command in bird.
https://github.com/Nordix/Meridio/issues/419
- Purpose
- Test

Gateway routes imported/exported/preferred metrics

---

docs/demo/scripts/kind/Dockerfile
docs/demo/scripts/kind/Makefile
docs/demo/scripts/kind/bird/bird-filler-net.conf
docs/demo/scripts/kind/bird/bird-gw-no-default.conf
test/e2e/environment/kind-operator/dualstack/configuration/conduit-destination-port-nats.yaml
test/e2e/environment/kind-operator/dualstack/configuration/flow-byte-matches.yaml
test/e2e/environment/kind-operator/dualstack/configuration/flow-destination-ports-range.yaml
test/e2e/environment/kind-operator/dualstack/configuration/flow-priority.yaml
test/e2e/environment/kind-operator/dualstack/configuration/init-trench-a.yaml
test/e2e/environment/kind-operator/dualstack/configuration/init-trench-b.yaml
test/e2e/environment/kind-operator/dualstack/configuration/new-attractor-nsm-vlan.yaml
test/e2e/environment/kind-operator/dualstack/configuration/new-flow.yaml
test/e2e/environment/kind-operator/dualstack/configuration/new-stream.yaml
test/e2e/environment/kind-operator/dualstack/configuration/new-vip.yaml
test/e2e/environment/kind-operator/dualstack/configuration/stream-max-targets.yaml

In kind environment e2e tests should cover gateway router setups where routers advertise non-default
routes instead of default routes.
Changes are straightforward, as they rely on external-host.sh script's existing `--default-route` parameter to decide on the setup. It can be configured through newly introduced KIND_EXTERNAL_HOST_DEFAULT_ROUTE parameter in docs/demo/scripts/kind/Makefile (defaults to `yes` i.e. default route advertisement).
example:
`make -s -C test/e2e/environment/kind-operator/ KUBERNETES_VERSION=v1.26 NSM_VERSION=v1.12.0 IP_FAMILY=dualstack KIND_EXTERNAL_HOST_DEFAULT_ROUTE=yes`
Note:
In kind-host image there's a dedicated BIRD config for the two cases. The networks currently advertised as non-default routes do work irrespective of the Trench or VLAN ID. (Changing the …

e2e; allow non-default route advertisement in kind environment

---

readme.md

Introduced with https://github.com/Nordix/Meridio/pull/467, some nftables features might not be supported before Kernel 5.2. (see [changelogs 9.2](https://wiki.nftables.org/wiki-nftables/index.php/List_of_updates_in_the_nft_command_line_tool), `Use variable to define jump / goto chain`)
Some traffic disturbance can happen prior Kernel 5.3.18 and 5.14.21
- Purpose
- Test

Update minimum Kernel version supported to 5.15

---

pkg/security/credentials/credentials.go

When using credentials pkg, a new X509 source was created upon each GetX509Source() call while the sources
were never closed thus the underlying resources were not released causing resource leakage (e.g. in the TAPA).
#500 
- Purpose
- Test

Fix X509 source leak in credentials pkg

---

cmd/frontend/internal/frontend/metrics.go
cmd/frontend/main.go
cmd/stateless-lb/main.go
docs/observability/dashboard.json
docs/observability/metrics.md
docs/observability/readme.md
pkg/kernel/metrics.go
pkg/loadbalancer/flow/metrics.go
pkg/loadbalancer/target/metrics.go
pkg/metrics/const.go

* meridio.conduit.stream.target.hits.METRIC_TYPE to meridio.conduit.stream.target.hit.METRIC_TYPE
* meridio.attracted.gateway.routes.METRIC_TYPE to meridio.attractor.gateway.METRIC_TYPE.routes
* Rename hostname from attributes since open telemetry SDK already adds the pod name
* meridio.attractor.gateway.routes.METRIC_TYPE type as gauge instead of counter
* Fix documentation and dashboard
- Purpose
- Test

Fix metrics names and attributes

---

build/stateless-lb/Dockerfile
pkg/loadbalancer/nfqlb/nfqlb.go

Set hash mode to 0 to load balance on tuple-5 using SCTP
https://github.com/Nordix/nfqueue-loadbalancer/pull/21
- Purpose
- Test

NFQLB Update to 1.2.0 to change hash mode

---

cmd/proxy/main.go
cmd/stateless-lb/main.go
pkg/kernel/bridge.go
pkg/kernel/interface.go
pkg/networking/ifaces.go
pkg/nsm/interfacemonitor/common.go
pkg/nsm/interfacemonitor/server_test.go
pkg/proxy/proxy.go

The so called nsm interfaceMonitor that is used by the Proxy for both its NSC and NSE connections from now on
forwards kernel originated interface delete events. This allows the Proxy to clean-up even if the network interface was no longer available by the time the associated NSM connection got closed.
(Thus, nexthop routes towards LBs can be removed in such cases.)
Note: Order of IP addresses in the IPContext might change between periodic NSM connection refreshes. Therefore, networking.Iface items must be compared by taking the above into consideration.
#517 
- Purpose
- Test

Reconfigure proxy on network interface delete events from kernel

---

cmd/ipam/config.go
cmd/proxy/internal/config/config.go
cmd/proxy/main.go
cmd/stateless-lb/main.go
cmd/tapa/main.go
docs/components/ipam.md
docs/components/nsp.md
docs/components/proxy.md
pkg/ambassador/tap/tap.go
pkg/ambassador/tap/trench/conduit.go
pkg/ambassador/tap/trench/configuration.go
pkg/ambassador/tap/trench/trench.go
pkg/health/connection/connection.go
pkg/loadbalancer/stream/loadbalancer.go
pkg/nsm/client.go
pkg/nsm/config.go
pkg/nsm/interfacename/cache.go
pkg/proxy/proxy.go

- Use environment variable Timeout to control NSM Request timeout in TAPA.
- Use GRPCMaxBackoff in nsmAPIClient as well to control max backoff in case of NSM Requests and such.
(By limiting max backoff NSM related operation might succeed earlier for example after an NSMgr outage.)
- Timer resource clean-up improvements.
N/A
- Purpose
- Test

NSM Request and API client improvements

---

cmd/ipam/config.go
cmd/ipam/main.go
config/templates/charts/meridio/deployment/ipam.yaml
deployments/helm/values.yaml
docs/components/ipam.md
pkg/controllers/trench/ipam.go
pkg/ipam/node/node.go
pkg/ipam/server.go
pkg/ipam/storage/logger/logger.go
pkg/ipam/storage/memory/memory.go
pkg/ipam/storage/sqlite/context.go
pkg/ipam/storage/sqlite/model.go
pkg/ipam/storage/sqlite/sqlite.go
pkg/ipam/types/types.go

Introduced garbage collection logic in IPAM to clean up IP records not updated for a long time and hence considered not in use anymore by any NSM connections.
For this the database model has been extended with UpdatedAt (timestamp) and Expirable (*bool) fields. UpdatedAt is used by newly introduced garbage collector logic along with a threshold time to determine if a record can be removed. While Expirable limits the scope of database records the garbage collector mechanism applies to. The check is run periodically. Both the threshold and periodicity interval are configurable through environment variables (IPAM_GARBAGE_COLLECTION_THRESHOLD and IPAM_GARBAGE_COLLECTION_INTERVAL).
As part of the changes node allocations do update existing database records to keep UpdatedAt values up to date. …

ipam; introduce garbage collection logic

---

cmd/proxy/internal/client/fullmesh.go
cmd/proxy/internal/service/client.go

Forgot to pass MaxTokenLifetime to fullmesh client to include it in the endpoint expiration check.
Follow-up for https://github.com/Nordix/Meridio/pull/538
https://github.com/Nordix/Meridio/issues/537
- Purpose
- Test

proxy; pass MaxTokenLifetime for expiration check

---

pkg/nsm/client.go

By default the ns and nse registry client uses a [dialtimeout of 300 mseconds](https://github.com/networkservicemesh/sdk/blob/release/v1.13.2/pkg/registry/chains/client/nse_client.go#L47) (might depend on the sdk version). This might put unnecessary load on the clients due to the frequent retries during nsmgr failover/upgrade.
Hence, pass the dialtimeout value configured for the container when creating the registry clients.
NA
- Purpose
- Test

Set dialtimeout for NS/NSE registry clients

---

cmd/proxy/internal/client/fullmesh.go
pkg/ambassador/tap/conduit/conduit.go
pkg/nsm/monitor/connection.go

Close MonitorConnection streaming RPC by cancelling the related context once done using it. Thus, avoiding memory leak like symstoms on the server side (NSMgr).
#545 
- Purpose
- Test

Close MonitorConnection streaming RPC

---

cmd/operator/main.go
docs/components/operator.md
docs/concepts/conduit.md
go.mod
pkg/controllers/common/action.go
pkg/controllers/common/const.go
pkg/controllers/conduit/conduit_controller.go
pkg/controllers/conduit/conduit_controller_test.go
pkg/controllers/conduit/proxy.go

Users can group Conduits into update groups by annotating Conduit Custom Resources with the `update-sync-group` key. Within an update group, Conduit updates are executed sequentially rather than in parallel.
The default annotation key can be changed via the operator environment variable `CONDUIT_UPDATE_SYNC_GROUP_KEY` when deploying the operator.
Locking is achieved using in-memory locks, which are fast and provide a sufficiently good solution. However, this approach is not effective in case of operator crashes during ongoing updates. Such crashes would be considered a bug to be fixed and should not occur in general.
The feature has support for changing the annotation value of a Conduit Custom Resource on the fly. (Including removing it completely.)
However, no immediate control can be …

operator; enable sequential conduit updates

---

pkg/controllers/attractor/stateless-lb-frontend.go
pkg/controllers/common/helper.go
pkg/controllers/conduit/proxy.go
pkg/controllers/trench/ipam-service.go
pkg/controllers/trench/ipam.go
pkg/controllers/trench/nsp-service.go
pkg/controllers/trench/nsp.go

Operator updates metadata labels and annotations (including spec.template) for proxy daemonset, stateless-lb deployment, nsp statefulset, and ipam statefulset workloads according to their deployment templates.
While for nsp service and ipam service their metadata labels and annotations are updated.
The update merges the existing labels and annotations with the ones found in the deployment templates so that values from templates overwrite existing entries. Labels and annotations not found in templates are left intact.
Note:
With the changes introduced by this PR, in case spec.template labels or annotations have to be aligned in accordance with the new deployment templates, then it will result in workload update even if there were no other changes.
NA
- Purpose
- Test
- Introduce a breaking …

operator; align labels/annotations with deployment templates

---

cmd/proxy/main.go
pkg/kernel/bridge.go
pkg/kernel/interface.go
pkg/proxy/proxy.go

Bridge interfaces must be properly set up and their IP addresses acquired during the proxy's startup sequence.
The startup phase now blocks until bridge IPs are successfully allocated.
Consequently, the NSE and NSC services of the proxy are not started until the bridge IPs are set. Without these services, the readiness and liveness probes would fail, which provides both visibility and means for recovery.
Note: This improvement is considered a low-hanging fruit to avoid some of the race condition related problems described in the linked issue.
#569
- Purpose
- Test

Block startup until bridge IP allocation succeeds

---

pkg/controllers/attractor/stateless-lb-frontend.go
pkg/controllers/conduit/proxy.go

Previously, the init container was always configured in the proxy and stateless-lb-frontend, even if not defined in the template. This change adds a check to ensure init container logic only runs when it is explicitly included in the Pod spec, preventing unnecessary init container injection.
- Purpose
- Test

Make init container configuration conditional in proxy and stateless-lb-frontend

---

cmd/frontend/main.go
cmd/ipam/main.go
cmd/nsp/main.go
cmd/operator/main.go
cmd/proxy/main.go
cmd/stateless-lb/main.go
cmd/tapa/main.go
pkg/log/logger.go
pkg/log/logger_test.go

This PR introduces support for changing the application's log level at runtime by sending configured OS signals, and wires this functionality into the cmd/*/main.go entrypoints. The motivation of this change is to enable easier debugging and runtime inspection without restarting the application.
- Added `SetupLevelChangeOnSignal` in `pkg/log/logger.go` to listen for
specified signals and adjust the zap logger's level dynamically.
- Added `WithNSMLogger` option to also update the `nsmLogger` when present.
- Integrated signal-based log level setup into all relevant `cmd/.../main.go`
files.
- `SIGUSR1` resets to the initial log level.
- `SIGUSR2` switches to `TRACE`.
- For commands using NSM logging, `WithNSMLogger` is passed to update both
loggers.
- Purpose
- Test
- Introduce a breaking …

Add dynamic log level change via signals and integrate into cmd entrypoints
